### ISSUE TITLE
Document "queryRaw doesn't support dynamic tables names"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2479]
Special case for raw queries: https://github.com/prisma/prisma/issues/9765#issuecomment-951742974

Impacted section: https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access

---

Update 8-jul-2022
Andrew: The solution for this has changed. Harshit has given me [some notes on this](https://prisma-company.slack.com/archives/D03P0UPS0QY/p1657267174671649)

**Comment by tanberry** [comment]
We could possibly cover this in the work of #2540 .

**Comment by andrew-walford-prisma** [comment]
I need to determine the best workaround for this issue. I've reached out to Harshit about this.

**Comment by andrew-walford-prisma** [comment]
> I need to determine the best workaround for this issue. I've reached out to Harshit about this.

He says: 

Looks like the API changed after I posted so types weren’t compatible for the users.
The problem here is that if you use the template literal version it will send the data as postgres prepared variables and that won’t be valid. We have a docs section explaining this exact case
You will need to use unsafe variant here in order to use the table name like so:

```
let userTable = "User";
  let result = await prisma.$queryRawUnsafe(
    `SELECT * FROM ${userTable}`,
  );
```

I'll need to include a warning about the risks of queryRawUnsafe
