### ISSUE TITLE
Make clearer that soft delete middleware is just a proof of concept, not our soft delete solution

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2508]
Update: 5-Sep-2022, Andrew W
I'm investigating, but my first instinct is that we should signpost this in the page title - something like "Middleware example: soft delete" and then put an admonition saying something like "This is an example of what you can do with middleware - it is not the official soft delete in Prisma". If we do that, we'll also need to make equivalent changes to the other middleware examples pages, for uniformity's sake.

https://www.prisma.io/docs/concepts/components/prisma-client/middleware/soft-delete-middleware

Our users regularly misunderstand that this is just a proof of concept of something you can do with a middleware, not the ultimate solution to implement soft deletes in Prisma: https://github.com/prisma/prisma/issues/3398#issuecomment-967783110 (and many more messages in that thread before)

We should fix that somehow.

**Comment by tanberry** [comment]
Options (possible some combo):
1. change the titles to be more descriptive, that it is only an example... but let's not use the word "example" maybe "sample use of middleware" ... since "example" implies the code snippet will indeed work in most cases.
2. remove the soft delete page all together (maybe ask Dev Adv if they want to blog about it)
3. leave the page there, and add qualifying sentences/caveats... the caveats could be a list of the known places where it does not work. Something at top of page, then the list. 
4. Ask the engineers to help update the code sample so that the list of what does not work... maybe we can reduce the number of things that do not work. (There is already a ticket ([#10559](https://github.com/prisma/prisma/issues/10559)) for engineering to work on fixing some of the items that do not work. Let's align our Docs effort with the work they do.

Perhaps we start with option number 1, and then do option number 3 now, then work with Devs to align on  option number 4.

Let's ask @andrewicarlson if he has data on how many people use this, and in what scenarios.

There are no Docs PRs on this.

**Comment by andrew-walford-prisma** [comment]
Tana and I have agreed to do 1 and 3 immediately, so the doc isn't misleading, and then research 4.

**Comment by andrew-walford-prisma** [comment]
I'm going to create a separate docs issue for 1 and 3, so that we can progress that work as a discrete unit.

Edit: here it is: https://github.com/prisma/docs/issues/3727

**Comment by andrew-walford-prisma** [comment]
We have the following list of possible exceptions with the soft delete middleware. However, we need to confirm these before we add them to the docs. In addition, we have an open engineering ticket that aims to fix some of this, which I'm monitoring. 

## Limitations

The soft delete sample on this page is not a full implementation. In the options above, we explain some of the limitations. Other limitations include the following:

- `findMany` with options such as `some` and `none` does not work
- Most nested queries, such as `findMany({ where: {}, include: {}})` and `update({data: { posts: { deleteMany: { } } } })` do not work
- [Cascading deletes](/guides/database/advanced-database-tasks/cascading-deletes) do not work
- You cannot update related tables with `updateMany`
- You cannot enforce [referential actions](/concepts/components/prisma-schema/relations/referential-actions)
- You cannot filter deleted relations
- You cannot use the sample in conjunction with a conditional unique index
