### ISSUE TITLE
QuickStart Guide: add steps for using migrate

### ISSUE THREAD

**Issue by tanberry** [prisma/prisma2-docs#2812]
See [thread](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1643797645876339) about this. Thanks @nikolasburk  for this suggestion.

**Comment by tanberry** [comment]
Joël's good idea about using `db push` for simplicity and pointing to migrate guide for people that need to commit migration files

**Comment by nikolasburk** [comment]
> Joël's good idea about using db push for simplicity and pointing to migrate guide for people that need to commit migration files

IMO we should favor Prisma Migrate here because that's the much more relevant workflow for people to learn about when first exposed to Prisma. They might also be curious about the SQL that Prisma sends to the DB which isn't made explicit with `prisma db push`.  

Personally, I consider `prisma migrate` the _default_ that people should be using/learning first and `prisma db push` an exception where it's about prototyping and quick experimental schema changes that they can discover according to the principle of [progressive disclosure of complexity](https://www.jason.af/progressive-disclosure-of-complexity/) later in their Prisma journey.

**Comment by ruheni** [comment]
This is done
