### ISSUE TITLE
Document how to use  ObjectIDs with raw queries on MongoDB

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma2-docs#2944]
Based on this issue: https://github.com/prisma/prisma/issues/12124

```ts
  const users = await prisma.user.findRaw({
        filter: {
            _id: { $eq: { $oid: "6202ec178be26d2b28adc075" } },
        },
    })
```

**Comment by ChristophP** [comment]
This just bit me and cost me quite some time to understand.
It was especially confusing because the exact same command worked in the mongo shell using `db.runCommand()`. So initially I thought it was a bug in Prisma.

 I finally managed to learn about it in [this issue](https://github.com/prisma/prisma/issues/12124) after much trial and error.
Would be great to have this documented.

**Comment by germanamz** [comment]
This should be documented in https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#runcommandraw

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
