### ISSUE TITLE
Navigation is often uncollapsed by default

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#2946]
Examples:
![image](https://user-images.githubusercontent.com/183673/156623660-c1bc7ffa-0165-4483-bd48-f2696a006079.png)
![image](https://user-images.githubusercontent.com/183673/156623679-5b9b4417-ed8b-4384-9aaf-fb3064f87ffe.png)

Internal discussion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1646300543748219

**Comment by carlagn** [comment]
I've yet to come with a solution for this issue but will leave some comments on discoveries made:

- The issue itself is not easy to replicate, as it happens without any specific precedent. 
- The main discrepancy noted during this investigation, especially on the situations where it managed to be replicated, the following has been noticed:
   - The `collapsed` prop is getting a mismatched list of bucketNames, as you can see on the following table:

| `bucketNames` on issue | `bucketNames` on regular cases | 
|---|---|
|<img width="805" alt="Screenshot 2022-06-07 at 10 39 42" src="https://user-images.githubusercontent.com/14851246/172349946-fee23978-3806-42a5-84e6-089b1ebacbad.png">|<img width="924" alt="Screenshot 2022-06-07 at 10 40 19" src="https://user-images.githubusercontent.com/14851246/172350018-f66c08d8-0363-4ffa-8ae0-a01db54c11c9.png">|

From this component-level view we can assume that the `bucketNames` are either:

1. Being overrun during run-time (this is likely since it's been sighted the visual change on the collapsed state even without refreshing the page or after entering it)
2. Fetching the `bucketNames` list incorrectly (unlikely, as the slug is still correct and so are the fetched `bucketEdges`, see image below for a `console.log(bucketName, bucketEdges)` on component `SidebarLayout`. 
<img width="552" alt="Screenshot 2022-06-07 at 10 48 51" src="https://user-images.githubusercontent.com/14851246/172350875-8a8d1c85-7add-48c5-aedd-3e3cb9d3fcb3.png">
  
The issue is likely to be lying on the way the collapsed list is being set, on the `TreeNode` component, as it defines the collapsed list, but is being sent the correct `label` prop from `treeData` component.
