### ISSUE TITLE
In MySQL the user must have SELECT rights for Prisma to work correctly

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma2-docs#2997]
MySQL is kind of funny. You can create and drop tables, but if you miss the select grant, you cannot list any columns from the tables you have.

Therefore, a user must have the `SELECT` grant with MySQL to be able to `db pull`, but also `db push` and `migrate dev` due to these commands also depending on `db pull`.

We should document this requirement. [Official docs](https://dev.mysql.com/doc/refman/5.7/en/grant.html).

**Comment by tanberry** [comment]
Thank you @pimeys this is a rather important point! A quick summary in my words so I am sure I understand: We need to make sure MySQL users know that in order to successfully use `db pull` `db push` and `db migrate`, they will need to make sure they have the correct permissions **at the column level**  in the table(s)... by running the `GRANT SELECT` command and specifying the exact columns, the privileges, the table name, etc.

**Comment by janpio** [comment]
`GRANT SELECT` should cover all tables and columns - no need to specify individually. But without that grant things go wrong.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
