### ISSUE TITLE
Example Schemas and Queries Docs Missing

### ISSUE THREAD

**Issue by haaarshsingh** [prisma/prisma2-docs#3104]
The [Example schemas and queries page](https://www.prisma.io/docs/guides/schema-query-examples) is blank.

The [GitHub page](https://github.com/prisma/docs/blob/main/content/300-guides/010-schema-query-examples/index.mdx) for this particular page also does not contain anything. 

I see a "hide page" set to "true" on the GitHub though, I'm not sure if it's the "hidePage" feature not working, but I thought I'd open this issue to alert someone anyways about the issue.

**Comment by ankur-arch** [comment]
Hey @haaarshsingh 👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏

I'm closing this issue as the pages don't exist anymore and hence this issue seems to be outdated, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏
