### ISSUE TITLE
Update Deploying to Netlify guide

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#3139]
See https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-netlify

Currently, has the following note:
```
Note: This deployment guide is outdated and will be updated soon.
```

But it's unclear 
- Is there info how exactly it is outdated?
- What are the plans to make it not outdated?

After a quick check I think what is outdated is the example repo, check that version :older_man:
https://github.com/prisma/deployment-example-netlify/blob/main/package.json
```
    "prisma": "2.24.1",
```

So it looks like someone will need to verify the full flow and update that repository.

We also found a doc issue about documenting [Next.js deployment](https://github.com/prisma/docs/issues/1879), but since this page is currently not using Next.js that could be done separately.

[See internal Slack thread](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1652167493889129)

**Comment by zachtil** [comment]
Here is a summary of the changes that I think should be done to update this guide:

**Changes to the Netlify Deployment example repository**

- Update Prisma and Prisma Client to their latest versions in package.json
- Add the `shadowDatabaseUrl` param to the `schema.prisma` file
- Update the Tailwind CSS link in index.html because with the current link the styling of the app is completely broken

All of these updates are in this [fork](https://github.com/zachtil/deployment-example-netlify-zach/commit/b420e0a30f3b441d418ca4fd36b1fe0be518c4f8).

**Changes to the Deployment guide contents**

- Remove the `psql` prereq and the `psql` steps as they are no longer needed. The repo comes with an existing model in `schema.prisma` so people should only need to run `npx prisma migrate dev --name init` to begin.
- Based on this, I am not sure if we even need the `prisma generate` in the overview given that it's unrelated to the overall task of deployment
- Add info about obtaining the Heroku PostgreSQL connection string (I've based this information on Heroku PostgreSQL as PostgreSQL was anyway pre-set in the `schema.prisma` file with the postgresql db connection.
- Add info about adding the shadow database in Heroku because this is required given that cloud db providers don't allow the auto-creation of those
- Remove 5. Introspect the database
- Remove 6. Commit the `schema.prisma` file

I am retesting these to see if I should add anything else to this list.
