### ISSUE TITLE
Link checker not working locally

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4005]
Broken links aren't being picked up when running `npm run dev` locally (they are on Vercel build though)

Slack conversation here: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1667574068196089

**Comment by zachtil** [comment]
@nilubava From the Slack message, you're saying to use `npm run clean && npm run build`.

Just to confirm: this seems to run well with `npm run build`. Can it also work with `npm run dev`?

**Comment by keerlu** [comment]
Could we get clarification about `npm run dev` please?

Previously we got the link checker results as part of our standard `npm run dev` local workflow, so we'd definitely see them. Do we now have to separately run `npm run build` if we want to check for broken links?

**Comment by nilubava** [comment]
Since the link checker plugin uses the gatsby cache for plugins, it does not seem to work on `npm run dev` as before (ie, before the updates) So the best way to run link-checker would be 
```
npm run clean && npm run build
```

`npm run build` may also work, but in order to make sure it works by clearing the cache and reporting the links correctly, it is better to do `npm run clean` too.

I am still working on finding the issue with this plugin on Vercel deployments (https://github.com/prisma/docs/issues/4084), but until we find an appropriate solution, it would be better if you can use the above cmd to check for broken links locally.
