### ISSUE TITLE
Link checker not running consistently on Vercel

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4084]
We're now seeing problems with the link checker running inconsistently on Vercel builds, so that broken links are making it into `main` without us realising.

Example:
- link checker fails: https://vercel.com/prisma/docs/9dji4SKgw3L8VKYMMTfpPWTPBnLB
- no link checker failure: https://vercel.com/prisma/docs/CkBXKHxNKhphs46RXLcmwSyGJtyb

Only difference between these builds is printing a different string when the link checker is run.

See [Slack thread](https://prisma-company.slack.com/archives/C02JV0K2Q31/p1668762943369889) for more details.

**Comment by nilubava** [comment]
Also, a new issue:

The PR `https://github.com/prisma/docs/pull/4236/files` caused a failure in the github action `ci.yml` due to link checker - https://github.com/prisma/docs/actions/runs/4017060499

Temp fix: make it report the broken links as a warning and continue with the next steps of the workflow. 

Todo: Make the link checker fail the build. Resolve the broken links reported


Context: https://prisma-company.slack.com/archives/C02JV0K2Q31/p1674722924837509
