### ISSUE TITLE
Prisma Client setup doc needs clarification

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4109]
On the [Prisma Client setup page](https://www.prisma.io/docs/concepts/components/prisma-client#3-use-prisma-client-to-send-queries-to-your-database), we provide two options, but do not say what they are. (TS vs. JS)

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1669017604941859

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
