### ISSUE TITLE
Consider removing the duplicated generators material and just linking to the main list of generators

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4121]
Our list of generators is duplicated:
- Docs setion: https://www.prisma.io/docs/concepts/components/prisma-schema/generators#community-generators
- Main Prisma site page: https://www.prisma.io/ecosystem

We could remove the list and simply link to the page on the main site.

Thread about this: https://www.prisma.io/docs/concepts/components/prisma-schema/generators#community-generators

However, Jan points out in that thread, users can do PRs on the docs page to add their own generators.

So we need to decide whether to remove the material in the docs section (and add a link) or not.

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
