### ISSUE TITLE
PDP: Connection strings

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4122]
During user testing, some of the respondents that interacted with the new onboarding shared that they'd find it useful to have a documentation link in the UI pointing to a page with the following information:

* Format of the connection string (in terms of UX, this will be handled with a placeholder in the **Connection string** input box)
* Required user & password
* List of supported database types
* Security
* Indication that PDP uses the connection string only to introspect the database
* Change / Update the database connection string - this will not be possible after the project is created

Size: M

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
