### ISSUE TITLE
Add docs on language tooling

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4174]
Add docs on language tooling.

Currently there is just the 'Editor setup' page in Guides:

https://www.prisma.io/docs/guides/development-environment/editor-setup#vs-code

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
