### ISSUE TITLE
Clarify `npm install` vs `npm install --force` in README

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4198]
Currently the docs repo README says to use `npm install`, but sometimes we need to use `npm install --force`. Saw someone else run into this problem yesterday.

It seems a bit odd to me that we need to use `--force`, but if we do the README should reflect that.

Previous Slack conversation here - https://prisma-company.slack.com/archives/C5Z9TH6N9/p1669117538997049?thread_ts=1669117038.047879&cid=C5Z9TH6N9

**Comment by janpio** [comment]
Optimally we should get rid of that need - it only makes things slower and smells that something is fundamentally broken.

**Comment by nilubava** [comment]
~~For the time being, we need to use `npm i --force` since there is a mismatch between the `gatby-plugin-mdx` and the main `gatsby` version. We are working on updating the `gatsby-plugin-mdx` to the latest available version so that we do not need the use of `--force` anymore. We suggest updating the `README` with this temporarily till the plugin is updated.~~

I have updated the `package.json` with the correct peer deps, so you can ignore this and keep `npm install` in README

**Comment by keerlu** [comment]
Confirming that this has been fixed now and we no longer need to use `--force`.
