### ISSUE TITLE
Extensions docs: consider feedback about multiple clients versus single client

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4239]
Here, Frederick makes a point about documenting multiple instances: https://prisma-company.slack.com/archives/C043X6JBND6/p1670575666880229

Here, Niko suggests code example changes to cover adding extensions upon instantiation of the client: https://prisma-company.slack.com/archives/C043X6JBND6/p1670489221725259

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
