### ISSUE TITLE
Consider adding matrix of prisma version x db version compatibility

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma2-docs#4241]
It would be helpful to have a matrix which demonstrates the compatibility of Prisma versions with Databases.

This can also be extended to demonstrate preview features timeline, this would help users in visualising the prisma versions from which the feature was in early access and from which version it went into GA.

**Comment by zachtil** [comment]
Hey @nurul3101 👋 

Thank you for submitting this! We'll take a look and see how we can create a compatibility matrix of Prisma versions and database versions.

In the meantime, we do have the list of Prisma preview features that are now generally available listed in two pages: 

- [Prisma Client preview features promoted to general availability](https://www.prisma.io/docs/concepts/components/preview-features/client-preview-features#preview-features-promoted-to-general-availability)
- [Prisma CLI preview features promoted to general availability](https://www.prisma.io/docs/concepts/components/preview-features/cli-preview-features#preview-features-promoted-to-general-availability)

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
