### ISSUE TITLE
Extensions: add section - 'Refer to the current client instance in an extension'

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4267]
In the root extensions page, add a section about how to refer to the current client instance in an extension. This is basically a more generalized version of the section we already have on Prisma.getExtensionContext(this) on the query page.

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
