### ISSUE TITLE
Query extensions: review the batch transaction example

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4357]
In our client extensions: query doc, we [give an example of batch transactions](https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions/query#wrap-a-query-into-a-batch-transaction). Jan has queried whether it's a realistic example, because it wraps a single `FindFirst` into a batch transaction, which might be the same as not wrapping it. I will ask Pierre to comment, because I think he provided the example. If this is indeed not realistic, we might want to provide a more realistic example, perhaps relating to RLS, which is mentioned as a key use case for this feature.

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
