### ISSUE TITLE
PDP: Document that `sslaccept=accept_ivalid_certs` is added to all db conn strings

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4359]
Background: https://prisma-company.slack.com/archives/C042HLMAC5U/p1669882940532849

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
