### ISSUE TITLE
PDP: Expand Query Console page

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#4403]
Expand [Query Console](https://www.prisma.io/docs/data-platform/query-console) page to include information about the fact that all Prisma Client queries are supported including `create` and `createMany`. Specific use cases are perhaps handled somewhat differently so caveats should also be documented.

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
