### ISSUE TITLE
Document how to use Prisma with unsupported database features

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma2-docs#4425]
The schema team are working on how to improve the experience of using database features that are not supported in Prisma, by including warnings on introspection that unsupported features are present. (Notion doc [here](https://www.notion.so/prismaio/Handling-unsupported-database-functionality-better-d73432c5177e4f4e90ce7f8441a0794a))

We'll need to improve the docs so that the warnings have something to link to, explaining that the feature is unsupported and providing any workaround that exist (e.g. manually add SQL to migration file).

Currently we have:
- a couple of sentences on [Unsupported database features](https://www.prisma.io/docs/concepts/components/prisma-schema/features-without-psl-equivalent#unsupported-database-features)
- the linked page on [Including unsupported features as part of a migration](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/include-unsupported-database-features)

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
