### ISSUE TITLE
Add docs for JSON protocol work

### ISSUE THREAD

**Issue by andrew-walford-prisma** [prisma/prisma2-docs#4447]
SME: Flavian

The docs changes will likely be:

- Document the preview feature flag, most likely `jsonProtocol`
- Document a new `engine_protocol = "graphql" | "json"` field. TBD whether it will go in the `generator` or `datasource` block

FAO @mcbethio

**Comment by mcbethio** [comment]
@sabinadams This is one Andrew had on his plate.

**Comment by mcbethio** [comment]
@SevInf can you pick this up with @sabinadams please.

**Comment by janpio** [comment]
There is no work to do for this in 4.10.0 yet, we will use release notes and GitHub issue instead.

**Comment by janpio** [comment]
PR now exists: https://github.com/prisma/prisma/pull/17911/files

Taking some notes here for things that possible should be documented (sooner or later, this might just live in an issue for the initial release):

- env var `PRISMA_ENGINE_PROTOCOL=graphql|json`
- Some validations disabled for now (so invalid queries could be run instaed of being caught, and returns database query errors instead of expected error message)

**Comment by sabinadams** [comment]
@janpio Are we still planning any docs related to this feature or can this issue be closed?

**Comment by janpio** [comment]
Probably only when it goes GA.
But we should check if it is listed in the preview features list. There it should be present already.

**Comment by sabinadams** [comment]
I've got a PR up that adds `jsonProtocol` to the Preview Features list. I would say we let that PR close this issue and open up a new one when we're ready to actually work on documenting it in GA.
