### ISSUE TITLE
Document network access of Prisma

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-docs#4679]
Can be based on https://prisma.slack.com/archives/C044YLSN49E/p1681933341507699?thread_ts=1681815921.969089&cid=C044YLSN49E

**Comment by ruheni** [comment]
Possibly related: https://github.com/prisma/docs/issues/1639

**Comment by jharrell** [comment]
👋 Hi there,
We're reviewing and tidying up our backlog to focus on the most relevant and impactful issues. After careful consideration, we're closing issues that haven't had any recent activity or align with our current priorities.
If you believe this issue is still important or unresolved, you're welcome to reopen it or create a new one with updated details. Your feedback is always valued and we're here to help ensure our docs continue to improve.
Thank you for your understand and contributions!
