### ISSUE TITLE
Help users when they need to use `pg_dump`: when a baselining is needed for a brownfield project.

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma2-docs#4906]
We mention `pg_dump` in https://github.com/prisma/docs/blob/99c5858661dc5284fd9e565476b41993f271bf7d/content/300-guides/025-migrate/100-developing-with-prisma-migrate/050-add-prisma-migrate-to-a-project.mdx?plain=1#L93

In a brownfield project when a user wants to manage their database with Prisma Migrate, a baseline migration is required (because there is an existing database).

`pg_dump` can be used to create a reliable baseline migration, example
```
pg_dump --file=migration.sql --schema-only --dbname=mydb --host=localhost --username=myuser --password
```

⚠️ The `migration.sql` dump needs to be edited and this following line removed.
```
SELECT pg_catalog.set_config('search_path', '', false);
```

If it is not removed, the migration will fail with the following error message:
```
Applying migration `20220510114355_baseline`
Error: P1014

The underlying table for model `_prisma_migrations` does not exist.
```

We could mention this somewhere in our docs.

**Comment by janpio** [comment]
What is the explanation behind this?

> If it is not removed, the migration will fail with the following error message:
> `The underlying table for model `_prisma_migrations` does not exist.`

How does that 1 SQL command lead to this error message?

**Comment by Jolg42** [comment]
Migrate relies on the `search_path` which is set to the current schema behind the scenes when connecting to the db.
Since the search path is modified during the migration, here to nothing, it causes this.

**Comment by janpio** [comment]
Doesn't that imply a potential bug in our logic reading `_prisma_migrations`, that we should specify the schema explicitly instead of relying on the search paths? (That would still work, correct?) Or alternatively, that we should detect such search path modifications and warn about them and maybe even prevent running migrate on such SQL files?

**Comment by robert-king** [comment]
I'm getting similar errors. It was complaining that _prisma_migrations doesnt exist, it created it in the correct schmea, but then in created all my tables in the public schema instead of the one specified in my database url.

export DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/kick_the_can?schema=prisma_raw_events
npx prisma migrate deploy --schema=./apps/thred-events-inserter/prisma/schema.prisma

also in the migrations.sql file, I have to go public.create_hypertable, as it doesn't find create_hypertable otherwise. It's not really documented but i assumed if i specified a specific schema in the database url, everything would just work and be restricted to that schema.

**Comment by Sjlver** [comment]
Detecting a change to the search path, as @janpio suggested, would be great. I had exactly the problem described in this issue, and it took a while to find the cause. It might be worth detecting since this is the default behavior of `pg_dump`.

That said, migrations could probably do a number of things that screw up Prisma. However, changes from `pg_catalog.set_config` are only valid in the current session. So a safer (albeit slower) way would be to run each migration in its own session. That is, create a new database connection for each. This makes migrations more isolated, and thus there are fewer assumptions about what they can and cannot do.
