### ISSUE TITLE
many-to-many query

### ISSUE THREAD

**Issue by jelmd** [prisma/prisma2-docs#5022]
Documentation on https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations is really bad, because it explains bloat but not the meat/what is usually needed, e.g. how to `select A from A,B where (B.aid=1 OR B.aid=2) and A.id = B.aid`. 

The examples shown are confusing, especially when unknown properties are used. E.g. in [
Querying an explicit many-to-many](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#querying-an-explicit-many-to-many): What the heck does the `..., category: { create: { name: 'New category', }, }, ...`. 

Hmmm, the category has no `create` property, does it? Why is it not possible to simply document plain CRUD? Would proper highlighting may help? 

And why all the **MongoDB bloat**? I think it is better to put it onto separate pages and add some links to it instead (e.g. I do not care about MongoDB at all - usually I use MySQL ...). 

So KISS, using consistent examples, and good examples like people register themselves at high school, high school announces collections of lectures, students subscribe to lectures - all separate actions (and finally create a study plan for student X and an attendance list for lecture Y) - would probably cover everything one needs to know to be able to handle many-to-many relationships with prisma ...

**Comment by nikolasburk** [comment]
Hey @jelmd 👋 thanks for the feedback on our m-n relations docs and apologies for the delayed response, we're only now getting to a major cleanup of the `docs` repo 🙏 

> because it explains bloat but not the meat/what is usually needed, e.g. how to select A from A,B where (B.aid=1 OR B.aid=2) and A.id = B.aid.

The page you've linked is primarily about _data modeling_ (although you're right that it does contain some query examples for convenience).

Maybe the [relation queries](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries) page would have been more useful in your case?

Also, we don't document queries like `select A from A,B where (B.aid=1 OR B.aid=2) and A.id = B.aid` because as an ORM, we're abstracting from SQL so you'll only find queries using the higher-level Prisma Client API.

> And why all the MongoDB bloat? I think it is better to put it onto separate pages and add some links to it instead (e.g. I do not care about MongoDB at all - usually I use MySQL ...).

Thanks for the feedback on this one too! We're currently considering adding a "DB switcher" to the docs that lets you pick your preferred DB and only shows the respective content.

I'll close this issue for now since we're not planning to make any changes to the relation docs for the time being 🙏 Please feel free to open another issue if you see any potential for improvement in our docs.
