### ISSUE TITLE
Request for Next.js.13 (App) router + Prisma documentation

### ISSUE THREAD

**Issue by GavinSalcedo** [prisma/prisma2-docs#5200]
### Discussed in https://github.com/prisma/prisma/discussions/20762

<div type='discussions-op-text'>

<sup>Originally posted by **GavinSalcedo** August 21, 2023</sup>
### Question

Is there an existing documentation for Next.js using the app directory integrating Prisma?

I understand this should be straightforward for Next.js developers to understand and migrate from pages to app, however, I think it would also benefit other developers if given more reference.

App router is becoming more stable and evidently effective than pages, so I would like to request to update the Prisma website documentation.

Thanks for the considering this post.

reference: https://www.prisma.io/docs/concepts/overview/prisma-in-your-stack/fullstack

### How to reproduce (optional)
Click on this link to access the existing documentation
- https://www.prisma.io/docs/concepts/overview/prisma-in-your-stack/fullstack

_No response_

### Information about Prisma Schema, Client Queries and Environment (optional)

_No response_</div>
```[tasklist]
### Tasks
```

**Comment by carvalhochris** [comment]
Hello

I have a working Next app router with Prisma: https://github.com/carvalhochris/pure-ts

**Comment by navdeep-soni** [comment]
> Hello
> 
> I have a working Next app router with Prisma: https://github.com/carvalhochris/pure-ts

I think the problem starts when you have to use common scenarios like add, delete, or fetch conditional data by clicking a button. The only way is to create API (route.ts) in the app folder and call them on the client side

**Comment by ankur-arch** [comment]
👋 Hi there, 

We’re taking some time to organize our backlog and focus on the most relevant and impactful issues. As part of this effort, we’re closing some issues that haven’t seen much recent activity or don’t align with our current focus. 

We do have an example of using Prisma with Next.js App Router, which you can check out [here](https://github.com/prisma/prisma-examples/tree/latest/accelerate/nextjs-starter). While this example uses Prisma Accelerate with Prisma ORM, you can easily use just Prisma ORM in the same way. 

If you feel this issue is still relevant or unresolved, please don’t hesitate to reopen it or create a new one with updated details. We truly value your feedback and are always here to help ensure our docs continue to improve.

Thank you for your understanding and for being part of our community!
