### ISSUE TITLE
docs: make it obvious that extensions don't work with nested reads/writes

### ISSUE THREAD

**Issue by shawnjones253** [prisma/prisma2-docs#5217]
I found this caveat buried in one of the [examples](https://github.com/prisma/prisma-client-extensions/blob/8661dbcf22456b603204246ca5dac65cd8264a36/input-validation/README.md#L9):

> **NOTE**: Query extensions do not currently work for nested operations. In this example, validations are only run on the top level `data` object passed to methods such as `prisma.product.create()`. Validations implemented this way do not automatically run for [nested writes](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#nested-writes).

This seems like a pretty important caveat that should be in a more-obvious place (perhaps the extension docs site).

**Comment by jkomyno** [comment]
Potentially related issue: https://github.com/prisma/prisma/issues/20780.

> I believe the issue is stemming from the fact that extensions don't allow for nested CRUD operations because that is essentially what a connect/disconnect/set through one of the models would be.
> What would the recommended workaround for this be?

**Comment by greg0x** [comment]
I have built a solution on the assumption that this works well. It was a big surprise when I had to realise that this feature really doesn't work for nested queries and then I have found these issues. 

My use case: I have introspected an existing database and generated a graphql api for it with [typegraphql prisma](https://prisma.typegraphql.com/). The generated api uses selects in nested queries. I am implementing an i18n layer for the api which will translate the api responses with the i18next package. To do so I need to modify the responses and replace the original content with the translated version. Originally I was using a result extension, but that's not good because in a nested query case the model names don't match. 

Example: I have locations which are also available through a regions model. The regions query is using select to include locations.

I have found 2.5 workarounds: 

## 1 use query extension and chain the modification
Inside the `then` the `params.__internalParams.dataPath["select", "<actual_model_name>"]`

```
prisma.$extends({
      name: 'debug',
      query: {
        $allModels: {
          $allOperations(params) {
            return params.query(params.args).then((res) => {
              console.log(
                '---',
                JSON.stringify(params, null, 2),
                JSON.stringify(res),
              )
              return res
            })
          },
        },
      },
    })
```

## 2 use a middleware 

The trick is the same, it's just easier to access the variable in `params.dataPath["select", "<actual_model_name>"]`

⚠️ Middlewares are deprecated

```
  prisma.$use(async (params, next) => {
    const result = await next(params)

    console.log('---', JSON.stringify(params))
    console.log('---', JSON.stringify(result))

    return result
  })
```

## 0.5

In the [applyAllResultExtensions](https://github.com/prisma/prisma/blob/fd5e07df7257431eba3a6175dc756169af095ef1/packages/client/src/runtime/core/extensions/applyAllResultExtensions.ts) the necessary infrastructure seems to be in place and since the [visitQueryResult](https://github.com/prisma/prisma/blob/fd5e07df7257431eba3a6175dc756169af095ef1/packages/client/src/runtime/core/extensions/visitQueryResult.ts#L15-L19) is meant to be recursively traversing the tree my assumption is that the current behavior is a bug. This function was introduced in [#20438](https://github.com/prisma/prisma/pull/20438).

**Comment by olivierwilkinson** [comment]
Hi all,

I have created a package that allows you to create extensions that work with nested operations: [prisma-extension-nested-operations](https://github.com/olivierwilkinson/prisma-extension-nested-operations). Writing extensions for nested operations means you need to account for the different format of nested operation args, so make sure to read the README and to test thoroughly before putting anything out to production 👍
