### ISSUE TITLE
Document "Cold starts" for Accelerate

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#5523]
We regularly have users who are confused about cold starts of Accelerate and individual queries taking 5-6 randomly. We should document this behaviour in the Accelerate docs (maybe under "Limitations").

**Comment by tylerwithpin** [comment]
What causes this behavior?

**Comment by curately** [comment]
I have been running into this a lot - what can be done about it?

**Comment by jharrell** [comment]
@tylerwithpin @curately could I ask what DB engines/providers you're using?

**Comment by curately** [comment]
Hi, I’m using mongoDB hosted on Atlas.

Best, Chris

**Comment by tylerwithpin** [comment]
@jharrell 

MongoDB hosted on Atlas, as well

**Comment by nurul3101** [comment]
@curately @tylerwithpin

This issue is caused due to a bug in MongoDB Rust Driver. We have reported the bug with all the details here: https://github.com/mongodb/mongo-rust-driver/issues/1170

MongoDB team has acknowledged the bug and created a Jira issue here: https://jira.mongodb.org/browse/RUST-1994

We are in touch with the MongoDB team and are taking measures to expedite this 🙏

**Comment by indie-ridge-dev** [comment]
Thanks @nurul3101

**Comment by nurul3101** [comment]
The cold start issue with MongoDB + Accelerate should be fixed in prisma version 5.19.0.

Please upgrade to version 5.19.0 to try out the fix 🙏
