### ISSUE TITLE
Misleading documentation - https://www.prisma.io/docs/orm/reference/prisma-schema-reference#unique-1

### ISSUE THREAD

**Issue by teodorrd27** [prisma/prisma2-docs#5640]
> Enforced by a compound index in MongoDB - you must create this index yourself

[Link to docs repo code](https://github.com/prisma/docs/blob/main/content/200-orm/500-reference/100-prisma-schema-reference.mdx#L2231)

Upon modifying a schema on one of our MongoDB models with ` @@unique([barcode, createdById])`, `prisma db push` created the compound index. i.e. we did not have to create it ourselves.

This is a good thing and the functionality is very useful, please don't remove it.
But could the docs be brought in line to reflect this functionality?

**Comment by nikolasburk** [comment]
Hey @teodorrd27 👋  thanks for opening this issue and apologies for the delay!

I've removed the "you must create this index yourself" from the docs and am closing this issue.

If you feel like this should be further clarified, feel free to re-open the issue with some more input or otherwise submit a PR directly 😄
