### ISSUE TITLE
Meta docs need updated structure

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma2-docs#5930]
The "meta" docs, hosted under `/about`, have a few layers of nesting and don't quite make sense. 

- https://www.prisma.io/docs/about/prisma-docs has content and acts as an index
- https://www.prisma.io/docs/about has no content and is an index
- https://www.prisma.io/docs/about/prisma-docs/about-the-docs has content, isn't an index

We should go through and clean up this section in addition to updating its content.

**Comment by nikolasburk** [comment]
I _think_ this is resolved by now since [prisma.io/docs/about/prisma-docs](https://www.prisma.io/docs/about/prisma-docs) and [prisma.io/docs/about/prisma-docs/about-the-docs](https://www.prisma.io/docs/about/prisma-docs/about-the-docs) are both 404s.

Feel free to re-open if more work needs to be done here, Jon 🙏
