### ISSUE TITLE
convert inline code strings to terminal code blocks in Getting Started

### ISSUE THREAD

**Issue by mendelssohnbach** [prisma/prisma2-docs#6108]
Thanks for publishing this very informative document.

[https://github.com/prisma/docs/blob/ae571304fd49da15382b2874859e22e3488208ef/content/100-getting-started/02-setup-prisma/100-start-from-scratch/120-mongodb/200-install-prisma-client-typescript-mongodb.mdx?plain=1#L24](https://github.com/prisma/docs/blob/ae571304fd49da15382b2874859e22e3488208ef/content/100-getting-started/02-setup-prisma/100-start-from-scratch/120-mongodb/200-install-prisma-client-typescript-mongodb.mdx?plain=1#L24)

If you can give us an example of a terminal, can make it clearer.

```terminal copy
npx prisma db push
```

**Comment by jharrell** [comment]
Thank you for the feedback! We use `terminal` code blocks in other areas of our docs and I agree that it should be updated here.

**Comment by nikolasburk** [comment]
Hey @mendelssohnbach 👋 thanks a lot for opening the issue! In this case, we only _mention_ the command in a sentence, it's intentionally not written in a dedicated code block because these are often interpreted as instructions.

I'm closing this issue. Please let me know if you have further questions and feel free to open more issues and PRs in the future 🙌
