### ISSUE TITLE
Nested upsert example missing `where` clause

### ISSUE THREAD

**Issue by jyasskin** [prisma/prisma2-docs#6274]
Sorry if I'm just misunderstanding this, but in https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#update-or-create-a-related-record, it looks like the `upsert` object has the required `create` and `update` fields, but it's missing the required `where` field.

**Comment by nikolasburk** [comment]
Hey @jyasskin 👋 

Thanks a lot for opening this issue! This is indeed a misunderstanding:

- you are referring the _query_ called `upsert` which indeed requires a `where` clause to identify the record that potentially gets updated
- however, this page is about the _option_ called `upsert` inside the _query_ called `update` and hence doesn't require a `where` clause (because the record to be updated is identified through the 1-n-relation)

You can test this by setting up a simple Prisma ORM project and this schema:

```prisma
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}
```

Then try to use the query you refer to in the docs and you'll see the behaviour as expected.

Let us know if you have any further questions, we're always happy to help 😄
